### ISSUE TITLE
💡[Feature] 개발환경 초기 세팅

### ISSUE THREAD

**Issue by dkjefilsjl** [Titubeobear/TBB_FE#4]
## 💡 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 개발환경 세팅

## 📝 기능 상세 내용

 - 프로젝트 생성
 - eslint, prettier 적용

## ✅ TODO

- [x] 프로젝트 생성
- [x] eslint, prettier 적용
