### ISSUE TITLE
💡[Feature] git 서버 연동

### ISSUE THREAD

**Issue by dkjefilsjl** [Titubeobear/TBB_FE#5]
## 💡 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- git 서버 연동

## 📝 기능 상세 내용

- git 서버 연동

## ✅ TODO

- [ ] git 서버 연동
