### ISSUE TITLE
💡[Feature] 파일 구조 생성

### ISSUE THREAD

**Issue by dkjefilsjl** [Titubeobear/TBB_FE#6]
## 💡 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 파일 구조 생성

## 📝 기능 상세 내용

- 파일 구조 생성

## ✅ TODO

- [ ] 파일 구조 생성
